/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eshi_bridge_sondklib_NdkTest */

#ifndef _Included_com_eshi_bridge_sondklib_NdkTest
#define _Included_com_eshi_bridge_sondklib_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eshi_bridge_sondklib_NdkTest
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eshi_bridge_sondklib_NdkTest_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
