/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eshi_bridge_sondklib_TestNdk */

#ifndef _Included_com_eshi_bridge_sondklib_TestNdk
#define _Included_com_eshi_bridge_sondklib_TestNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eshi_bridge_sondklib_TestNdk
 * Method:    setUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eshi_bridge_sondklib_TestNdk_setUp
  (JNIEnv *, jobject);

/*
 * Class:     com_eshi_bridge_sondklib_TestNdk
 * Method:    setA
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_eshi_bridge_sondklib_TestNdk_setA
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_eshi_bridge_sondklib_TestNdk
 * Method:    getStringFromNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_eshi_bridge_sondklib_TestNdk_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_eshi_bridge_sondklib_TestNdk
 * Method:    isB
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_eshi_bridge_sondklib_TestNdk_isB
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
